data:
  start_date: "2024-08-01"
  max_iter: 30
  stock_list:
    - AAPL
    - MSFT
    - GOOGL
    # - AMZN
    # - META
  history_window: 100
  data_dir: "./data"
  result_dir: "./result"

problem:
  start_budget: 1000
  lam: 0.1
  beta: 0.001

solvers:
  # - tensor_network
  # - scip
  # - quantum_annealing
  - qaoa

quantum_annealing:
  alpha: 5.0
  bits_per_asset: 2
  bits_slack: 8
  time: 10
  steps: 100
  traverse: 1.0
  transact_opt: "exact"
  # noise:
  #   type: depolarizing
  #   p1: 0.001
  #   p2: 0.01
  #   readout: 0.02
  use_gpu: false

qaoa:
  alpha: 5.0
  bits_per_asset: 3
  bits_slack: 8
  transact_opt: "exact"
  p: 1
  shots: 1000
  n_trials: 1
  maxiter: 100
  grad_delta: 0.01
  init_spread: 0.0
  seed: null
  optimization_algorithm: "SPSA"
  grad_method: "param_shift"
  noise: null
  use_gpu: false

tensor_network:
  alpha: 5.0
  bits_per_asset: 3
  bits_slack: 8
  transact_opt: "exact"
  method: "dmrg"
  mps_rank: 10
  mps_bond_dim: 20
  mps_opt: 1
  mps_seed: 1

scip:
  upper_bounds: 8
  suppress_output: true
