data:
  start_date: "2024-08-01"
  max_iter: 3
  stock_list:
    - AAPL
    - MSFT
    - GOOGL
    - AMZN
    - META
  history_window: 100
  data_dir: "./data"
  result_dir: "./result"

problem:
  start_budget: 500
  lam: 0.1
  beta: 0.001

solvers:
  - qaoa
  - quantum_annealing
  - tensor_network
  - scip

quantum_annealing:
  alpha: 5.0
  bits_per_asset: 2
  bits_slack: 4
  time: 10
  steps: 100
  traverse: 1.0
  transact_opt: "quadratic"
  # noise:
  #   type: depolarizing
  #   p1: 0.001
  #   p2: 0.01
  #   readout: 0.02
  use_gpu: false

qaoa:
  alpha: 5.0
  bits_per_asset: 2
  bits_slack: 2
  transact_opt: "quadratic"
  p: 10
  shots: 1000
  n_trials: 2
  maxiter: 50
  grad_delta: 0.01
  init_spread: 0.0
  seed: null
  optimization_algorithm: "L-BFGS-B"
  grad_method: "estimator"
  noise: null
  use_gpu: false

tensor_network:
  alpha: 5.0
  bits_per_asset: 2
  bits_slack: 8
  transact_opt: "exact"
  method: "dmrg"
  mps_rank: 10
  mps_bond_dim: 20
  mps_opt: 1
  mps_seed: 1

scip:
  upper_bounds: 8
  suppress_output: true
